\hypertarget{struct_o_s_c_internal_error}{}\doxysection{OSCInternal\+Error Struct Reference}
\label{struct_o_s_c_internal_error}\index{OSCInternalError@{OSCInternalError}}


{\ttfamily \#include $<$juce\+\_\+\+OSCTypes.\+h$>$}

Inheritance diagram for OSCInternal\+Error\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=3.000000cm]{d8/d4e/struct_o_s_c_internal_error}
\end{center}
\end{figure}
\doxysubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{struct_o_s_c_internal_error_ab61d68be60573c87ecaec312f2b0ddff}{OSCInternal\+Error}} (\mbox{\hyperlink{zconf_8in_8h_a2c212835823e3c54a8ab6d95c652660e}{const}} \mbox{\hyperlink{class_string}{String}} \&desc)
\end{DoxyCompactItemize}
\doxysubsection*{Additional Inherited Members}


\doxysubsection{Detailed Description}
Exception type thrown in cases of unexpected errors in the OSC module.

Note\+: This should never happen, and all the places where this is thrown should have a preceding jassertfalse to facilitate debugging.

@tags\{OSC\} 

\doxysubsection{Constructor \& Destructor Documentation}
\mbox{\Hypertarget{struct_o_s_c_internal_error_ab61d68be60573c87ecaec312f2b0ddff}\label{struct_o_s_c_internal_error_ab61d68be60573c87ecaec312f2b0ddff}} 
\index{OSCInternalError@{OSCInternalError}!OSCInternalError@{OSCInternalError}}
\index{OSCInternalError@{OSCInternalError}!OSCInternalError@{OSCInternalError}}
\doxysubsubsection{\texorpdfstring{OSCInternalError()}{OSCInternalError()}}
{\footnotesize\ttfamily OSCInternal\+Error\+::\+OSCInternal\+Error (\begin{DoxyParamCaption}\item[{\mbox{\hyperlink{zconf_8in_8h_a2c212835823e3c54a8ab6d95c652660e}{const}} \mbox{\hyperlink{class_string}{String}} \&}]{desc }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}



The documentation for this struct was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
build/juce\+\_\+osc/osc/\mbox{\hyperlink{juce___o_s_c_types_8h}{juce\+\_\+\+OSCTypes.\+h}}\end{DoxyCompactItemize}
